### ISSUE TITLE
run the main.py

### ISSUE THREAD

**Issue by xdg2016** [VisualComputingInstitute/TrackR-CNN#1]
Hello, thank for your works. I try to run the main.py in pycharm, but the code exits like this:
![image](https://user-images.githubusercontent.com/16351823/59652052-bf408080-91be-11e9-8717-e0a590d796fc.png)
I am sure that I have installed those packages mentioned, but I can't run the code successfully!
Can you tell me why? Thank you very much!

**Comment by pvoigtlaender** [comment]
Hi,

you have to specify a config file to run, e.g. python main.py configs/conv3d_sep2

**Comment by xdg2016** [comment]
Thanks for your  reply, I ran the main.py just like the demo script, but still has the save error,I tracked the code and found the point that cause the error:  **import pycocotools.mask as cocomask**。I used the pip to install the pycocotools 
![image](https://user-images.githubusercontent.com/16351823/59658148-6e885200-91d5-11e9-83e6-4ed24c5a2009.png)
However, I can't import the package. Besides,these codes could also cause the error:
![image](https://user-images.githubusercontent.com/16351823/59658561-962bea00-91d6-11e9-84f2-7b406805ba73.png)
because these codes also import the pycocotools package
I will try to reinstall the pycocotools! 
@pvoigtlaender

**Comment by xdg2016** [comment]
I have addressed the problem mentioned above, but I had other problems。
1、According to the parameters given in demo script, I ran the main.py and found that your project was organized under Linux，some file paths could not be found。Could you please elaborate on the data sets need to be downloaded to run demo successfully and how to organize the directory?
2、How could I test with my vedio?
Thank you very much!

**Comment by lalalabiubiu** [comment]
Hello, how do you solve the problem of importing packages? I am experiencing a similar problem, ImportError: cannot import name 'deconv_output_length', I guess it is my tensorflow and Python version. Which version of tensorflow and Python are you using? I look forward to your reply, thank you very much!

**Comment by xdg2016** [comment]
Hello, my tensorflow version is 1.13.1 with gpu, python=3.5.2. I addressed the import problem by recompiling the pycocotools with vc14. The vc version in my computer is vc12, however the pycocotools in windows must be compiled with vc14.

**Comment by lalalabiubiu** [comment]
Thank you very much for your reply, I will use this method to try to solve my problem.@xdg2016

**Comment by pvoigtlaender** [comment]
> Thanks for your reply, I ran the main.py just like the demo script, but still has the save error,I tracked the code and found the point that cause the error: **import pycocotools.mask as cocomask**。I used the pip to install the pycocotools
> ![image](https://user-images.githubusercontent.com/16351823/59658148-6e885200-91d5-11e9-83e6-4ed24c5a2009.png)
> However, I can't import the package. Besides,these codes could also cause the error:
> ![image](https://user-images.githubusercontent.com/16351823/59658561-962bea00-91d6-11e9-84f2-7b406805ba73.png)
> because these codes also import the pycocotools package
> I will try to reinstall the pycocotools!
> @pvoigtlaender

Hi,

I think these import issues should be fixable by adding the current path (root folder of TrackR-CNN) to your PYTHONPATH. Please let me know if that works for you.

**Comment by pvoigtlaender** [comment]
> 1、According to the parameters given in demo script, I ran the main.py and found that your project was organized under Linux，some file paths could not be found。Could you please elaborate on the data sets need to be downloaded to run demo successfully and how to organize the directory?

Hi,

please follow the instructions in the README:
You'll need to adjust the KITTI_segtrack_data_dir and load_init flags to point to the KITTI MOTS data directory, you can download KITTI MOTS from here:
https://www.vision.rwth-aachen.de/page/mots

**Comment by pvoigtlaender** [comment]
> Hello, how do you solve the problem of importing packages? I am experiencing a similar problem, ImportError: cannot import name 'deconv_output_length', I guess it is my tensorflow and Python version. Which version of tensorflow and Python are you using? I look forward to your reply, thank you very much!

This looks like it might be a problem with the TensorFlow version. Maybe try a slighly different/earlier version? Definitely do not use TensorFlow 2.0.

**Comment by DaxiongAI** [comment]
hi!,i follow the readme and run Forwarding and tracking code ,but i get this error

> Traceback (most recent call last):
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension size, given by scalar input 0, must be non-negative but is -1 for 'testnet/tower_gpu_0/conv3d_1/split' (op: 'Split') with input shapes: [], [1,5,23,77,1024] and with computed input tensors: input[0] = <-1>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    tf.app.run(main)
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 34, in main
    engine = Engine(config)
  File "/home/daxiong/TrackR-CNN/core/Engine.py", line 55, in __init__
    reuse_variables=reuse_variables)
  File "/home/daxiong/TrackR-CNN/network/Network.py", line 17, in __init__
    self._towers = self._build_towers(config, dataset, is_trainnet, freeze_batchnorm, reuse_variables)
  File "/home/daxiong/TrackR-CNN/network/Network.py", line 68, in _build_towers
    tower = NetworkTower(config, tower_setup, input_tensors_dict_sliced, dataset)
  File "/home/daxiong/TrackR-CNN/network/NetworkTower.py", line 65, in __init__
    layer = self._create_layer(name, layer_def, tower_setup, input_tensors_dict, dataset)
  File "/home/daxiong/TrackR-CNN/network/NetworkTower.py", line 145, in _create_layer
    layer = class_(**layer_def)
  File "/home/daxiong/TrackR-CNN/network/ConvolutionalLayers.py", line 302, in __init__
    curr_split = tf.split(curr, n_features_inp, axis=-1)
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1214, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3261, in _split
    num_split=num_split, name=name)
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/daxiong/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension size, given by scalar input 0, must be non-negative but is -1 for 'testnet/tower_gpu_0/conv3d_1/split' (op: 'Split') with input shapes: [], [1,5,23,77,1024] and with computed input tensors: input[0] = <-1>.
@pvoigtlaender

**Comment by xdg2016** [comment]
Thank you, I recompiled the pycocotools source code with vc14，and it works. I have another question:
If I want to use my trained YOLOv3 detector, and test on my video, how should I modify the code to use your TrackR-CNN, and is TrackR-CNN a online method?
@pvoigtlaender

**Comment by pvoigtlaender** [comment]
@xdg2016 TrackR-CNN is a near-online method (because the 3D convs look a few frames into the future). If you need an online variant, you can just leave the 3D convs out, which changes the results only slightly (shown in the paper).

TrackR-CNN includes a detector, so if you want to use YOLOv3, then there's no real point anymore in using TrackR-CNN

**Comment by pvoigtlaender** [comment]
@DaxiongAI From the stacktrace it's hard to see for me what's going on. Do you have any further useful information to figure out what's wrong? Which TensorFlow version are you using? Maybe you can step through with the debugger and try to gather some information?

**Comment by shoutOutYangJie** [comment]
> Thank you, I recompiled the pycocotools source code with vc14，and it works. I have another question:
> If I want to use my trained YOLOv3 detector, and test on my video, how should I modify the code to use your TrackR-CNN, and is TrackR-CNN a online method?
> @pvoigtlaender

now you can run it successfully, right? I am trying to test it. what problems should I notice?

**Comment by ahnonay** [comment]
Closing this due to inactivity, please reopen if needed.
