### ISSUE TITLE
Training interruption problem

### ISSUE THREAD

**Issue by 1wanttoknow** [VisualComputingInstitute/TrackR-CNN#48]
I have 2 GPU , I had a mistake when I started training. Has anyone encountered the same error? How can I resolve it?
..........
starting training
I1203 10:05:56.184263 140066288711488 Log.py:34] starting training
    8 / 39544 {loss:  0.78003} elapsed 45.849170207977295
I1203 10:06:42.033973 140066288711488 Log.py:34]     8 / 39544 {loss:  0.78003} elapsed 45.849170207977295
...
   24 / 39544 {loss:   1.0996} elapsed 14.851442575454712
I1203 10:07:15.374087 140066288711488 Log.py:34]    24 / 39544 {loss:   1.0996} elapsed 14.851442575454712
2019-12-03 10:07:19.467476: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: indices[15] = [15, 1] does not index into param shape [16,1,4]
..........
2019-12-03 10:07:19.674195: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: indices[15] = [15, 1] does not index into param shape [16,1,4]
Traceback (most recent call last):
  File "/home/lab509/miniconda3/envs/mots/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/lab509/miniconda3/envs/mots/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/lab509/miniconda3/envs/mots/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[15] = [15, 1] does not index into param shape [16,1,4]
         [[{{node trainnet/tower_gpu_0/frcnn_5/GatherNd}}]]

**Comment by ahnonay** [comment]
Can you confirm that training works when using only one gpu? There is a config flag "gpus" which you can try setting to 2, however this is untested. All of our results where obtained using one gpu.

**Comment by 1wanttoknow** [comment]
thank you ! The problem has been solved.

**Comment by zack624** [comment]
> thank you ! The problem has been solved.

Hello, I have the same problem as you, could you tell how to solve it?

**Comment by zack624** [comment]
> > thank you ! The problem has been solved.
> 
> Hello, I have the same problem as you, could you tell how to solve it?

Oh, my tensorflow-gpu isn't installed successfully.

**Comment by zhongzhuoyao** [comment]
I have encountered the same error when using only one gpu. I confirm that I have installed tensorflow-gpu successfully. Could you please give me some advice?

**Comment by ahnonay** [comment]
This is difficult to say, could be a problem with data not loaded correctly or using the wrong tensorflow version or other things. Please open a separate issue with a detailed description if the problem persists
