### ISSUE TITLE
Probelm about using 16bit  single channel image as input

### ISSUE THREAD

**Issue by LiXm1002** [VisualComputingInstitute/TrackR-CNN#49]
Dear author, I have tried make own dataset using 16bit single channel depth image as input, these pictures are then rendered into color pictures for annotation. I use the depth image and the annotation to train track r-cnn. I have change `img = tf.image.decode_image(img_data, channels=3)` to` img = tf.image.decode_image(img_data, channels=1)` in Dataset.py. The network can be trained normally. But when testing there are some error:
```
Forwarding video...
0000
1 / 108
Traceback (most recent call last):
  File "/media/ubuntu/SSD/TrackR-CNN/TrackR-CNN-master/main.py", line 39, in <module>
    tf.app.run(main)
  File "/home/ubuntu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/media/ubuntu/SSD/TrackR-CNN/TrackR-CNN-master/main.py", line 35, in main
    engine.run()
  File "/media/ubuntu/SSD/TrackR-CNN/TrackR-CNN-master/core/Engine.py", line 93, in run
    TrackingForwarder(self).forward()
  File "/media/ubuntu/SSD/TrackR-CNN/TrackR-CNN-master/forwarding/tracking/TrackingForwarder.py", line 92, in forward
    super(TrackingForwarder, self).forward()
  File "/media/ubuntu/SSD/TrackR-CNN/TrackR-CNN-master/forwarding/RecurrentDetectionForwarder.py", line 51, in forward
    self._forward_video(n_timesteps, tag)
  File "/media/ubuntu/SSD/TrackR-CNN/TrackR-CNN-master/forwarding/tracking/TrackingForwarder.py", line 146, in _forward_video
    recurrent_state, measures, extractions = self._forward_timestep(recurrent_state)
  File "/media/ubuntu/SSD/TrackR-CNN/TrackR-CNN-master/forwarding/RecurrentDetectionForwarder.py", line 94, in _forward_timestep
    extraction_keys=self._extraction_keys)
  File "/media/ubuntu/SSD/TrackR-CNN/TrackR-CNN-master/core/Trainer.py", line 151, in validation_step
    self.validation_step_number)
  File "/media/ubuntu/SSD/TrackR-CNN/TrackR-CNN-master/core/Trainer.py", line 188, in _step
    res = self.session.run(ops, feed_dict=feed_dict, options=run_options, run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (480, 640) for Tensor 'images_placeholder_0:0', which has shape '(?, ?, 3)'
```
I don't know where the problem is, I hope someone can help me.Thanks very much.

**Comment by ahnonay** [comment]
As the error message indicates, the network expects input tensors with a final dimension of size 3 (corresponding to colors). I think tensors with a final dimension of size 1 will also work and simply be tiled three times along the last dimension. So here, you would probably need to put an expand_dims statement behind decode_image.
Note however, that the pretrained weights aren't used to processing depth images so they will probably be rather useless in this scenario
