### ISSUE TITLE
Tuning - Can't find data in directory + path

### ISSUE THREAD

**Issue by emjay73** [VisualComputingInstitute/TrackR-CNN#58]
I tried tuning section as follows, 
```
 python scripts/segtrack_tune_experiment.py /home/emjay/Documents/MOTS/TrackR-CNN/forwarded/conv3d_sep2/detections/5 ﻿/home/emjay/Documents/MOTS/TrackR-CNN/data/KITTI_MOTS/train/instances /home/emjay /home/emjay/Documents/MOTS/TrackR-CNN/tuning/output_file ﻿/home/emjay/Documents/MOTS/TrackR-CNN/tuning/tmp_folder/ /home/emjay/Documents/MOTS/mots_tools/mots_eval reid 1000
```

and got errors like this,
```
Traceback (most recent call last):
  File "eval.py", line 45, in <module>
    run_eval(results_folder, gt_folder, seqmap_filename)
  File "eval.py", line 25, in run_eval
    gt = load_sequences(gt_folder, seqmap)
  File "/home/emjay/Documents/MOTS/mots_tools/mots_common/io.py", line 28, in load_sequences
    assert False, "Can't find data in directory " + path
AssertionError: Can't find data in directory ﻿/home/emjay/Documents/MOTS/TrackR-CNN/data/KITTI_MOTS/train/instances
[('0000', 154), ('0001', 447), ('0003', 144), ('0004', 314), ('0005', 297), ('0009', 803), ('0011', 373), ('0012', 78), ('0015', 376), ('0017', 145), ('0019', 1059), ('0020', 837)] False
Traceback (most recent call last):
  File "eval.py", line 45, in <module>
    run_eval(results_folder, gt_folder, seqmap_filename)
  File "eval.py", line 25, in run_eval
    gt = load_sequences(gt_folder, seqmap)
  File "/home/emjay/Documents/MOTS/mots_tools/mots_common/io.py", line 28, in load_sequences
    assert False, "Can't find data in directory " + path

```

Can I get a tip for that?
On top of that, is this a correct formation of directory hierarchy?

```
data
└── KITTI_MOTS
    └── train
        ├── images -> somewhere/KITTI_MOTS/Images/training/image_02
        └── instances -> somewhere/KITTI_MOTS/Annotations_in_png_format/instances

```

**Comment by emjay73** [comment]
I somehow solved it,
exchanging instances_image to instances_txt

```
python scripts/segtrack_tune_experiment.py /home/emjay/Documents/MOTS/TrackR-CNN/forwarded/conv3d_sep2/detections/5 /home/emjay/Documents/MOTS/TrackR-CNN/data/KITTI_MOTS/train/instances_txt /home/emjay /home/emjay/Documents/MOTS/TrackR-CNN/tuning/output_file /home/emjay/Documents/MOTS/TrackR-CNN/tuning/tmp_folder/ /home/emjay/Documents/MOTS/mots_tools/mots_eval reid 1000
```
