### ISSUE TITLE
Training stops

### ISSUE THREAD

**Issue by Snehabahl123** [VisualComputingInstitute/TrackR-CNN#95]
I am trying to train the model from scratch but after a lot of warnings and loading of files. It ends up showing that it is loading a model and a message about the training starting at epoch 6 and the code just stops ready to move onto the next block,
![1](https://user-images.githubusercontent.com/18510037/95038490-e2f94400-06eb-11eb-8198-2be34697bbb7.png)
![2](https://user-images.githubusercontent.com/18510037/95038496-e55b9e00-06eb-11eb-96aa-50069fc66c34.png)

**Comment by ahnonay** [comment]
The model from the website has been loaded here and since it is already trained, the training stops and moves on to the tracking stage.
If you want to train from scratch instead, you can copy the conv3d_sep2 config and change the "model" setting in the config to some other name. Then the trained model will no longer be loaded.

**Comment by YasuThompson** [comment]
I followed the instruction, and changed the part
 "model": "conv3d_sep2"
in "conv3d_sep2" in "configs" directory to
 "model": "conv3d_sep2_temp"

And then I got this error

`starting training
    8 / 39544 {loss:  0.71741} elapsed 240.5729420185089
2020-10-10 23:21:57.691068: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[15] = [15, 1] does not index into param shape [16,1,4]
2020-10-10 23:21:57.727916: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[15] = [15, 1] does not index into param shape [16,1,4]
2020-10-10 23:21:57.943834: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[15] = [15, 1] does not index into param shape [16,1,4]
2020-10-10 23:21:58.230097: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[15] = [15, 1] does not index into param shape [16,1,4]
2020-10-10 23:22:12.174556: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[15] = [15, 1] does not index into param shape [16,1,4]
2020-10-10 23:22:14.388323: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[15] = [15, 1] does not index into param shape [16,1,4]
2020-10-10 23:22:14.421444: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[15] = [15, 1] does not index into param shape [16,1,4]
2020-10-10 23:22:24.199817: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[15] = [15, 1] does not index into param shape [16,1,4]
Traceback (most recent call last):
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[15] = [15, 1] does not index into param shape [16,1,4]
	 [[{{node trainnet/tower_gpu_0/frcnn_1/GatherNd}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/main.py", line 39, in <module>
    tf.app.run(main)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/main.py", line 35, in main
    engine.run()
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/core/Engine.py", line 81, in run
    self.train()
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/core/Engine.py", line 112, in train
    train_measures = self.run_epoch(self.trainer.train_step, self.train_data, epoch, is_train_run=True)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/core/Engine.py", line 144, in run_epoch
    res = step_fn(epoch, n_examples_processed_total=n_examples_processed_total, extraction_keys=extraction_keys)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/core/Trainer.py", line 168, in train_step
    res = self._step(self.train_network, feed_dict, ops, self.summary_op_train, extraction_keys, step_number=None)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/core/Trainer.py", line 188, in _step
    res = self.session.run(ops, feed_dict=feed_dict, options=run_options, run_metadata=run_metadata)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[15] = [15, 1] does not index into param shape [16,1,4]
	 [[node trainnet/tower_gpu_0/frcnn_1/GatherNd (defined at /Users/tamurataito/Documents/lab/track_r_cnn/just_run/network/FasterRCNN_utils.py:392) ]]

Caused by op 'trainnet/tower_gpu_0/frcnn_1/GatherNd', defined at:
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/main.py", line 39, in <module>
    tf.app.run(main)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/main.py", line 34, in main
    engine = Engine(config)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/core/Engine.py", line 41, in __init__
    name="trainnet")
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/network/Network.py", line 17, in __init__
    self._towers = self._build_towers(config, dataset, is_trainnet, freeze_batchnorm, reuse_variables)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/network/Network.py", line 68, in _build_towers
    tower = NetworkTower(config, tower_setup, input_tensors_dict_sliced, dataset)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/network/NetworkTower.py", line 65, in __init__
    layer = self._create_layer(name, layer_def, tower_setup, input_tensors_dict, dataset)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/network/NetworkTower.py", line 145, in _create_layer
    layer = class_(**layer_def)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/network/FasterRCNN.py", line 184, in __init__
    self._create_heads(batch_idx, fm_anchors, fm_shape, rpn_box_logits, inputs, rpn_label_logits)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/network/FasterRCNN.py", line 305, in _create_heads
    rpn_label_logits)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/network/FasterRCNN.py", line 371, in _create_losses
    tf.gather(fastrcnn_box_logits, fg_inds_wrt_sample))
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/network/FasterRCNN_utils.py", line 392, in fastrcnn_losses
    fg_box_logits = tf.gather_nd(fg_box_logits, indices)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3647, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Users/tamurataito/Documents/lab/track_r_cnn/just_run/venv_4/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[15] = [15, 1] does not index into param shape [16,1,4]
	 [[node trainnet/tower_gpu_0/frcnn_1/GatherNd (defined at /Users/tamurataito/Documents/lab/track_r_cnn/just_run/network/FasterRCNN_utils.py:392) ]]


Process finished with exit code 1`


Is this because of my use of CPU?

P.S.
Are you planning to upload this implementation in Tensorflow 2?
Otherwise do you have advice on running this on a remote server with a Docker container?
